/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_slc_lib_osg_SwtOsgPart */

#ifndef _Included_org_argeo_slc_lib_osg_SwtOsgPart
#define _Included_org_argeo_slc_lib_osg_SwtOsgPart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_slc_lib_osg_SwtOsgPart
 * Method:    doBackendInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_argeo_slc_lib_osg_SwtOsgPart_doBackendInit
  (JNIEnv *, jclass);

/*
 * Class:     org_argeo_slc_lib_osg_SwtOsgPart
 * Method:    doInit
 * Signature: (IIIIF)J
 */
JNIEXPORT jlong JNICALL Java_org_argeo_slc_lib_osg_SwtOsgPart_doInit
  (JNIEnv *, jclass, jint, jint, jint, jint, jfloat);

/*
 * Class:     org_argeo_slc_lib_osg_SwtOsgPart
 * Method:    doDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_argeo_slc_lib_osg_SwtOsgPart_doDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_argeo_slc_lib_osg_SwtOsgPart
 * Method:    doPaint
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_argeo_slc_lib_osg_SwtOsgPart_doPaint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_argeo_slc_lib_osg_SwtOsgPart
 * Method:    doResize
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_argeo_slc_lib_osg_SwtOsgPart_doResize
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_argeo_slc_lib_osg_SwtOsgPart
 * Method:    doMouseMoveEvent
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_argeo_slc_lib_osg_SwtOsgPart_doMouseMoveEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_argeo_slc_lib_osg_SwtOsgPart
 * Method:    doMousePressEvent
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_argeo_slc_lib_osg_SwtOsgPart_doMousePressEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_argeo_slc_lib_osg_SwtOsgPart
 * Method:    doMouseReleaseEvent
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_argeo_slc_lib_osg_SwtOsgPart_doMouseReleaseEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_argeo_slc_lib_osg_SwtOsgPart
 * Method:    doMouseDoubleClickEvent
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_argeo_slc_lib_osg_SwtOsgPart_doMouseDoubleClickEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_argeo_slc_lib_osg_SwtOsgPart
 * Method:    doMouseWheelEvent
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_argeo_slc_lib_osg_SwtOsgPart_doMouseWheelEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
