/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_api_uuid_libuuid_DirectLibuuidFactory */

#ifndef _Included_org_argeo_api_uuid_libuuid_DirectLibuuidFactory
#define _Included_org_argeo_api_uuid_libuuid_DirectLibuuidFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_api_uuid_libuuid_DirectLibuuidFactory
 * Method:    timeUUID
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_argeo_api_uuid_libuuid_DirectLibuuidFactory_timeUUID
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
